POST https://httpbin/post
User-Agent: My User Agent
Content-Type: application/json
[BasicAuth]
alice: secret

```xml
<something> something </somethingsad>
<something> else </something>
<something>
	<nested-something> blah </nested-something>
</something>
```

POST https://httpbin/post
User-Agent: My User Agent
Content-Type: application/json
[BasicAuth]
alice: secret

```json
{
	"some": "json"
}
```

